name: Building + release depthcharge image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release-depthcharge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Installing dependencies
        run: sudo apt-get install -y cgpt vboot-kernel-utils parted
      - name: Cloning repositories
        run: |
          git clone --depth=1 https://github.com/eupnea-linux/postinstall-scripts.git
          git clone --depth=1 https://github.com/eupnea-linux/audio-scripts.git
          git clone --depth=1 https://github.com/eupnea-linux/eupnea-theme.git
          git clone --depth=1 https://chromium.googlesource.com/chromiumos/third_party/linux-firmware

      - name: Create temp directory
        run: mkdir /tmp/hyperos/

      - name: Downloading kernel, modules, headers
        run: |
          curl -L "https://github.com/eupnea-linux/kernel/releases/latest/download/bzImage" -o /tmp/hyperos/bzImage
          curl -L "https://github.com/eupnea-linux/kernel/releases/latest/download/modules.tar.xz" -o /tmp/hyperos/modules.tar.xz
          curl -L "https://github.com/eupnea-linux/kernel/releases/latest/download/headers.tar.xz" -o /tmp/hyperos/headers.tar.xz

      - name: Building depthcharge image
        run: python3 build_depthcharge.py -v

      - name: Splitting rar
        run: |
          split --verbose -b 1900MB HyperOS.bin.rar HyperOS.split.

      - name: Generating release tag and setting prerelease + name
        id: tag
        run: |
          if echo $(git log -1 --pretty=format:"%s") | grep -c "stable"
          then
            echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"
            echo "::set-output name=release_type::false"
          else
            echo "::set-output name=release_tag::dev-build" 
            echo "::set-output name=release_type::true"
          fi
          echo "::set-output name=commit_message::$(git log -1 --pretty=format:"%s")"

      - name: Deleting old dev release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1
          name: Image build - HyperOS
          prerelease: stable
          body: |
            This is stable
            Just extract the rar files and flash the image
            
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          #          files: |
          #            eupnea-depthcharge.bin.tar.xz
          #            eupnea-depthcharge.bin.rar
          files: |
            eupnea-depthcharge.split.*
